name: Release / Pull request
description: >
  Commits all modified files to a new release branch and creates a pull request
  towards the default branch (e.g. `main`).
author: Steffen Diswal

inputs:
  gh-auth-token:
    description: >
      An access token for GitHub with scopes for `repo` and `read:org` in order
      to create a pull request.
    required: true
  #
  version:
    description: >
      A string that contains a semantic version number on the
      form `<major.minor.patch[-prerelease][+buildinfo]>`.
    required: true

# https://github.com/cli/cli/issues/5896#issuecomment-1780072370
runs:
  using: composite
  steps:
    # language=sh
    - run: |
        VERSION=$(echo "$RAW_VERSION" | grep --only-matching --extended-regexp '[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?')
        REMOTE=$(git remote | head -n 1)

        if [[ -z "$GH_AUTH_TOKEN" ]]; then
          echo 'Input parameter `gh-auth-token` must be defined.'
          exit 2
        elif [[ -z "$VERSION" ]]; then
          echo 'Input parameter `version` must contain a semantic version number on the form `<major.minor.patch[-prerelease][+buildinfo]>`.'
          exit 2
        fi

        git checkout -b "release/$VERSION"
        git add .
        git commit --message "Prepare the release of $VERSION"
        git push --set-upstream "$REMOTE" "release/$VERSION"

        git fetch "$REMOTE" "$DEFAULT_BRANCH"
        gh auth login --with-token <<< "$GH_AUTH_TOKEN"
        gh pr create --title "Release $VERSION" --body 'This pull request was created automatically by GitHub Actions.'
      env:
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        GH_AUTH_TOKEN: ${{ inputs.gh-auth-token }}
        RAW_VERSION: ${{ inputs.version }}
      shell: bash
