name: Release / Major tag
description: >
  Creates and pushes a major-only version tag in Git from the commit that
  triggered the workflow.
author: Steffen Diswal

inputs:
  version:
    description: >
      A string that contains a semantic version number on the
      form `<major.minor.patch[-prerelease][+buildinfo]>`.
    required: true

runs:
  using: composite
  steps:
    # language=sh
    - run: |
        VERSION=$(echo "$RAW_VERSION" | grep --only-matching --extended-regexp '[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?')
        REMOTE=$(git remote | head -n 1)

        if [[ -z "$VERSION" ]]; then
          echo 'Input parameter `version` must contain a semantic version number on the form `<major.minor.patch[-prerelease][+buildinfo]>`.'
          exit 2
        fi

        MAJOR_VERSION=$(echo "$VERSION" | cut -d '.' -f 1)

        git tag --force --annotate --message "Release $VERSION" "v$MAJOR_VERSION"
        git push "$REMOTE" "v$MAJOR_VERSION" --force
      env:
        RAW_VERSION: ${{ inputs.version }}
      shell: bash
