name: Release / GitHub
description: Creates a draft GitHub release from a release tag.
author: Steffen Diswal

inputs:
  gh-auth-token:
    description: An access token for GitHub with scopes for `repo` and `read:org` in order to create a GitHub release.
    required: true
  #
  version:
    description: A string that contains a semantic version number on the form `<major>.<minor>.<patch>[-prerelease][+buildinfo]`.
    required: true

runs:
  using: composite
  steps:
    # language=sh
    - run: |
        VERSION=$(echo "$RAW_VERSION" | grep --only-matching --extended-regexp '[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?')

        if [[ -z "$GH_AUTH_TOKEN" ]]; then
          echo 'Input parameter `gh-auth-token` must be defined.'
          exit 2
        elif [[ -z "$VERSION" ]]; then
          echo 'Input parameter `version` must contain a semantic version number on the form `<major>.<minor>.<patch>[-prerelease][+buildinfo]`.'
          exit 2
        fi

        gh auth login --with-token <<< "$GH_AUTH_TOKEN"
        gh release create --draft --verify-tag --title "$VERSION" --notes 'This release was created automatically by GitHub Actions.' "v$VERSION"
      env:
        GH_AUTH_TOKEN: ${{ inputs.gh-auth-token }}
        RAW_VERSION: ${{ inputs.version }}
      shell: bash
