name: Release / Tag
description: >
  Creates and pushes a full semantic version tag in Git from the commit
  that triggered the workflow.
author: Steffen Diswal

inputs:
  version:
    description: >
      A string that contains a semantic version number on the
      form `<major.minor.patch[-prerelease][+buildinfo]>`.
    required: true

runs:
  using: composite
  steps:
    # language=sh
    - run: |
        VERSION=$(echo "$RAW_VERSION" | grep --only-matching --extended-regexp '[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?')
        REMOTE=$(git remote | head -n 1)

        if [[ -z "$VERSION" ]]; then
          echo 'Input parameter `version` must contain a semantic version number on the form `<major.minor.patch[-prerelease][+buildinfo]>`.'
          exit 2
        fi

        git tag --annotate --message "Release $VERSION" "v$VERSION"
        git push "$REMOTE" "v$VERSION"
      env:
        RAW_VERSION: ${{ inputs.version }}
      shell: bash
